### ISSUE TITLE
hardware to use, Arduino or Raspberry Pi?

### ISSUE THREAD

**Issue by Daksol** [demogorgi/set-rtc-using-dcf77-via-dcf1#1]
Hi.
Looks a neat project.

Couple of questions

#1  I think that the device shown is an Arduino. Any specific model?
#2 Would same code work on a Raspberry Pi? (apart from changing GPIO pin numbers etc)

Thanks

**Comment by demogorgi** [comment]
Hi,

> 1. I think that the device shown is an Arduino. Any specific model?

It's not an Arduino, but a WEMOS D1 mini Pro v1.1.0

> 2. Would same code work on a Raspberry Pi? (apart from changing GPIO pin numbers etc)

It should work on a Raspberry Pi without major modifications if you install MicroPython on it (https://github.com/boochow/micropython-raspberrypi/wiki/Quick-reference-for-the-Raspberry-Pi-Zero---W-MicroPython). If you run Linux on the RPi it should be possible to port the scripts from micropython to python.

Best regards
