### ISSUE TITLE
Module with inverted logic

### ISSUE THREAD

**Issue by varna9000** [demogorgi/set-rtc-using-dcf77-via-dcf1#2]
Hi, I've got a dcf77 module with inverted logic output. I tried to invert output Pin values like so  `v = not dcfpin.value()` and feed the data into the library but it always fails the parity check. Any idea what else need to be changed to get your library work with inverted bits module?

**Comment by demogorgi** [comment]
Hi, "not ..." yields a boolean. Try abs(dcfpin.value()-1) probably? It is
also important that you have a good signal strength. Test your setup
outside if possible. Best regards and good luck.

**Comment by varna9000** [comment]
I removed your comments in some part of the code to print the receiving bits. It looks like "not" operator reverses them, but will try your suggestion as well. On a second note, I tried some Arduino libraries with my module and it looks the signal is quite noisy. I'm around 1600 km from signal source and I suspect there is quite interference on the way to me, so I might not be lucky to get this working.
